export const products = [
  {
    id: 1,
    name: "Цветочный мёд",
    price: 18,
    originalPrice: 20,
    image: "/images/pic-card1.jpg",
    rating: 4.8,
    reviews: null,
    description: "Чистый цветочный мёд, собранный с местных лугов",
    badge: "Хит продаж",
  },
  {
    id: 2,
    name: "Гречишный мёд",
    price: 19,
    originalPrice: null,
    image: "/images/pic-card4.jpg",
    rating: 4.9,
    reviews: null,
    description: "Премиальный мёд с высоким содержанием MGO",
    badge: "Премиум",
  },
  {
    id: 3,
    name: "Падевый мёд",
    price: 21,
    originalPrice: null,
    image: "/images/pic-card3.jpg",
    rating: 4.7,
    reviews: null,
    description: "Лёгкий и мягкий мёд, идеален для ежедневного использования",
    badge: null,
  },
  {
    id: 4,
    name: "Медовые соты",
    price: 24,
    originalPrice: 30,
    image: "/images/pic-card2.jpg",
    rating: 5,
    reviews: null,
    description: "Натуральные медовые соты прямо из улья",
    badge: "Сырой и натуральный",
  }
]