export const products = [
  {
    id: 1,
    name: "Липовый мёд",
    price: 20,
    originalPrice: null,
    image: "/images/pic-card1.jpg",
    rating: 4.8,
    reviews: null,
    description: "Чистый липовый мёд, собранный с местных лугов",
    badge: "Хит продаж",
  },
  {
    id: 2,
    name: "Гречишный мёд",
    price: 20,
    originalPrice: null,
    image: "/images/pic-card4.jpg",
    rating: 4.9,
    reviews: null,
    description: "Премиальный мёд с высоким содержанием MGO",
    badge: "Премиум",
  },
  {
    id: 3,
    name: "Лесной мёд",
    price: 20,
    originalPrice: null,
    image: "/images/pic-card3.jpg",
    rating: 4.7,
    reviews: null,
    description: "Лёгкий и мягкий мёд, идеален для ежедневного использования",
    badge: null,
  },
  {
    id: 4,
    name: "Рапсовый мёд",
    price: 20,
    originalPrice: null,
    image: "/images/pic-card5.jpeg",
    rating: 4.7,
    reviews: null,
    description: "Натуральный, ароматный и мягкий мед с легким цветочным вкусом",
    badge: null,
  },
  {
    id: 5,
    name: "Медовые соты",
    price: 50,
    originalPrice: 55,
    image: "/images/pic-card2.jpg",
    rating: 5,
    reviews: null,
    description: "Натуральные медовые соты прямо из улья",
    badge: "Натуральный",
  }
]